apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: zipkin-ai
  name: zipkin-ai
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: zipkin-ai
    spec:
      containers:
      - env:
        - name: STORAGE_TYPE
          value: applicationinsights
        - name: AI_INSTRUMENTATION_KEY
          value: <foo>
        - name: AI_APPLICATION_ID
          value: <bar>
        - name: AI_API_KEY
          value: <baz>
        - name: SELF_TRACING_ENABLED
          value: "true"
        image: marcote/zipkin-ai:v3
        name: zipkin-ai
        ports:
        - containerPort: 9411
        resources: {}
      restartPolicy: Always
status: {}
